stages:
  - build
  - test

image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf libsdl2-dev libsdl2-ttf-dev doxygen zip
  script:
    - make -f Makefile.withAllCommands -j4
    - make -f Makefile.withAllCommands zip
  artifacts:
    name: "TPOHB"
    paths:
      - horanvoj
      - horanvoj.zip
    expire_in: 1 week
test:
    stage: test
    before_script:
      - apt update && apt -y install make autoconf libsdl2-dev libsdl2-ttf-dev doxygen zip
    script:
      - make -f Makefile.withAllCommands clean
      - make -f Makefile.withAllCommands test -j4

